### ISSUE TITLE
Android: (Calling js method onScanCompleted failed) when saveToGallery is true

### ISSUE THREAD

**Issue by wired4code** [NativeScript/nativescript-camera#39]
I'm having an issue with my Android build where if I set `saveToGallery` to `true`, after taking a picture and selecting it, rather than display it on the view, the app crashes with the following error below. But when it's set to false, the picture is taken, selected and shows up fine in my view.

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onScanCompleted failed

TypeError: trace.isEnabled is not a function
File: "file:///data/data/org.nativescript.kidquest/files/app/tns_modules/nativescript-camera/nativescript-camera.js, line: 63, column: 50

StackTrace: 
	Frame: function:'onScanCompleted', file:'file:///data/data/org.nativescript.camera-app/files/app/tns_modules/nativescript-camera/nativescript-camera.js', line: 63, column: 51

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.access$2400(Runtime.java:33)
	at com.tns.Runtime$3.run(Runtime.java:1214)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
in the logcat, I noticed this:

```
TNS.Native: Failed to load snapshot: dlopen failed: library "libsnapshot.so" not found
```
Oddly, this issue does not occur with my iOS build. Here is my source code:

```
import { Observable } from 'data/observable';
import { takePicture, requestPermissions } from 'nativescript-camera';
import * as imageSourceModule from "image-source";

export class CameraModel extends Observable {

    currentImage: any

    constructor() {
        super();
        requestPermissions();
    }

    takePhoto (args) {
        let self = this;
        takePicture({ width: 180, height: 180, keepAspectRatio: false, saveToGallery: true})
            .then((imageAsset) => {
                console.log("IMAGE ASSET:", imageAsset);
                let source = new imageSourceModule.ImageSource();
                source.fromAsset(imageAsset).then((source) => {
                    console.log(`Size: ${source.width}x${source.height}`);
                })
                self.set('currentImage', imageAsset);
            }, (error) => {
                console.log("Error: " + error)
            });
    }
}
```
Here is the main-page.ts file:

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { CameraModel } from './main-view-model';

export function navigatingTo(args: EventData) {
  
    let page = <Page>args.object;
    page.bindingContext = new CameraModel();
}
```

And finally, the xml file:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="Camera App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

       <StackLayout class="p-20">
        <Image src="{{ currentImage }}" id="image" stretch="aspectFit" margin="10"/>
        <Button text="TAKE PHOTO" tap="{{ takePhoto }}" class="btn btn-primary btn-active"/>
    </StackLayout>
</Page>
```

Everything works great if `saveToGallery` is set to `false`, but not when it's set to true. Is there something I'm doing wrong? 

The project was created using the tns typescript template and then I added the native-script camera plugin.

**Comment by NathanaelA** [comment]
The new version of the Camera module; you need to be using the v3.00 of the core modules-- If you use 2.5, it will fail with the above error.   I believe the prior v0.0.8 works with tns 2.5...

**Comment by wired4code** [comment]
That makes sense. I was just now checking out the 3.0.0 release candidate. I'll give that a go. Thanks!

UPDATE: That was it. I created a new template app with the 3.0.0-rc and everything working great!
