### ISSUE TITLE
[Crash] After taking more then three pictures on a device with Android API level 24 or later

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-camera#59]
The Issue could be reproduced while taking four pictures in sequence while using Android device with API level 24 or later. The application will crash with the following error:
```
System.err: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3453, result=-1, data=null} to activity {com.A2ZFieldServices.FieldCompass/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onActivityResult failed

System.err: 
System.err: Error: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.A2ZFieldServices.FieldCompass/files/NSIMG_20170927_152028.jpg (No such file or directory)

System.err:     java.io.FileInputStream.open(Native Method)

System.err:     java.io.FileInputStream.<init>(FileInputStream.java:146)
System.err:     java.io.FileInputStream.<init>(FileInputStream.java:99)
System.err:     android.media.ExifInterface.<init>(ExifInterface.java:1106)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)

System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:929)

System.err:     com.tns.NativeScriptActivity.onActivityResult(NativeScriptActivity.java:69)
System.err:     android.app.Activity.dispatchActivityResult(Activity.java:6942)
System.err:     android.app.ActivityThread.deliverResults(ActivityThread.java:4102)
System.err:     android.app.ActivityThread.handleSendResult(ActivityThread.java:4149)
System.err:     android.app.ActivityThread.-wrap20(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)

System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6154)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)

System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
System.err: File: "file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/nativescript-camera/nativescript-camera.js, line: 79, column: 35

System.err: 
System.err: StackTrace: 

System.err: 	Frame: function:'', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/nativescript-camera/nativescript-camera.js', line: 79, column: 36
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err: 	Frame: function:'ActivityCallbacksImplementation.onActivityResult', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 673, column: 44
System.err: 	Frame: function:'NativeScriptActivity.onActivityResult', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 41, column: 25
System.err: 
System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4106)
System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4149)
System.err: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6154)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onActivityResult failed
System.err: 

System.err: Error: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.A2ZFieldServices.FieldCompass/files/NSIMG_20170927_152028.jpg (No such file or directory)
System.err:     java.io.FileInputStream.open(Native Method)
System.err:     java.io.FileInputStream.<init>(FileInputStream.java:146)
System.err:     java.io.FileInputStream.<init>(FileInputStream.java:99)
System.err:     android.media.ExifInterface.<init>(ExifInterface.java:1106)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     com.tns.NativeScriptActivity.onActivityResult(NativeScriptActivity.java:69)
System.err:     android.app.Activity.dispatchActivityResult(Activity.java:6942)
System.err:     android.app.ActivityThread.deliverResults(ActivityThread.java:4102)
System.err:     android.app.ActivityThread.handleSendResult(ActivityThread.java:4149)
System.err:     android.app.ActivityThread.-wrap20(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6154)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
System.err: File: "file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/nativescript-camera/nativescript-camera.js, line: 79, column: 35
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/nativescript-camera/nativescript-camera.js', line: 79, column: 36
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err: 	Frame: function:'ActivityCallbacksImplementation.onActivityResult', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 673, column: 44
System.err: 	Frame: function:'NativeScriptActivity.onActivityResult', file:'file:///data/data/com.A2ZFieldServices.FieldCompass/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 41, column: 25
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err: 	at com.tns.NativeScriptActivity.onActivityResult(NativeScriptActivity.java:69)
System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:6942)
System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4102)
System.err: 	... 9 more
System.err: Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.A2ZFieldServices.FieldCompass/files/NSIMG_20170927_152028.jpg (No such file or directory)
System.err: 	at java.io.FileInputStream.open(Native Method)
System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:99)
System.err: 	at android.media.ExifInterface.<init>(ExifInterface.java:1106)
System.err: 	... 18 more
JS: App crashed:
JS: Error: The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.


```
I am attaching sample project, which could be used for debugging.

[project.zip](https://github.com/NativeScript/nativescript-camera/files/1343261/project.zip)

t. 1132625

**Comment by nmongiya** [comment]
I am using the 
https://github.com/NathanaelA/nativescript-permissions
This is a workaround, It has a function to check permission and return true and false.
permissions.hasPermission(permissionName);

permissionName - The permission you are requesting.
returns Boolean - true or false

**Comment by pauly815** [comment]
Observing this issue as well.  Not able to consistently replicate the error though.

**Comment by andreacappadona17** [comment]
Having the same error here.

**Comment by demetrio812** [comment]
This could be connected with this one: https://github.com/NativeScript/nativescript-camera/issues/63

**Comment by shiv19** [comment]
@demetrio812 @andreacappadona17 I feel this is related to removing the event listener before attaching it. So, it should be fixed by now.

Waiting for the next release of this plugin on npmjs

**Comment by DimitarTachev** [comment]
I'm closing this one as it's not reproducible with the latest version of the plugin.

Most probably @shiv19 is right and it has been related to the event listener fix.
